# Generated by Django 4.0.3 on 2022-04-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
